server:
  port: ${SERVER_PORT}


spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  liquibase:
    change-log: classpath:/db/changelog/master.yml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
    show-sql: false
  mvc:
    log-request-details: false
  freemarker:
    expose-session-attributes: true
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    jdbc:
      dialect: postgresql
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
      location: ./data


logging:
  level:
    root: info
    org:
      springframework:
        security: debug
      hibernate:
        stat: debug
        type: trace
    sql: trace
    web: debug
  file:
    name: logs/demo.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 5

#okta:
#  oauth2:
#    issuer: https://${}/
#    client-id: {yourClientId}
#    client-secret: YOUR_CLIENT_SECRET