--liquibase formatted sql
--changeset Bubunur:insert_pizzerias

insert into pizzerias(name, location_id)
values ('Борисов-1', (select id from locations where locations.name = 'Беларусь')),
       ('Полоцк-1', (select id from locations where locations.name = 'Беларусь')),
       ('Нововолоцк-1', (select id from locations where locations.name = 'Беларусь')),
       ('Орша-1', (select id from locations where locations.name = 'Беларусь')),
       ('Тучково-1', (select id from locations where locations.name = 'Деревни')),
       ('Котельники-1', (select id from locations where locations.name = 'Деревни')),
       ('Кубинка-1', (select id from locations where locations.name = 'Деревни')),
       ('Отрадное-1', (select id from locations where locations.name = 'Деревни')),
       ('ВНИИССОК-1', (select id from locations where locations.name = 'Деревни')),
       ('Пыть-Ях-1', (select id from locations where locations.name = 'Золотое Кольцо')),
       ('Кострома-1', (select id from locations where locations.name = 'Золотое Кольцо')),
       ('Кострома-2', (select id from locations where locations.name = 'Золотое Кольцо')),
       ('Иванова-2', (select id from locations where locations.name = 'Золотое Кольцо')),
       ('Иванова-3', (select id from locations where locations.name = 'Золотое Кольцо')),
       ('Иванова-1', (select id from locations where locations.name = 'Золотое Кольцо')),
       ('Москва 13-1', (select id from locations where locations.name = 'Москва')),
       ('Москва 13-2', (select id from locations where locations.name = 'Москва')),
       ('Москва 13-3', (select id from locations where locations.name = 'Москва')),
       ('Москва 13-4', (select id from locations where locations.name = 'Москва')),
       ('Калининград-4', (select id from locations where locations.name = 'Калининград')),
       ('Тверь-1', (select id from locations where locations.name = 'Тверь')),
       ('Тверь-2', (select id from locations where locations.name = 'Тверь')),
       ('Тверь-3', (select id from locations where locations.name = 'Тверь')),
       ('Тверь-4', (select id from locations where locations.name = 'Тверь')),
       ('Торжок-1', (select id from locations where locations.name = 'Тверь')),
       ('Вышний Волочёк-1', (select id from locations where locations.name = 'Тверь')),
       ('СПб 2-2', (select id from locations where locations.name = 'Санкт-Петербург')),
       ('СПб 2-7', (select id from locations where locations.name = 'Санкт-Петербург')),
       ('Усинск-1', (select id from locations where locations.name = 'УСП')),
       ('Печора-1', (select id from locations where locations.name = 'УСП')),
       ('Сосногорск-1', (select id from locations where locations.name = 'УСП')),
       ('Реутов-1', (select id from locations where locations.name = 'Московская область'));