--liquibase formatted sql
--changeset Bubunur:insert_criterion

insert into criteria(zone_id, section_id, description, coefficient)
values
    ((select id from zones where name = ''), (select id from sections where name = ''), 'Форма всех сотрудников соответствует стандарту. Сотрудники кухни (кассир при работе на упаковке) с бородой на всех станциях носят набородник', default),
    ((select id from zones where name = ''), (select id from sections where name = ''), 'Менеджер смены делает обходы.', default),
    ((select id from zones where name = ''), (select id from sections where name = ''), 'Сотрудники не используют личные телефоны в зеленой зоне пиццерии, не носят их в карманах', default),
    ((select id from zones where name='Потери'), (select id from sections where name=''), 'Продукт готовится по стандарту. Соблюдаются стандарты начинения, приготовления продукта, упаковки.  Нет перерасхода ингредиентов. До 3-х ошибок, 4 и более - крит. фактор', default),
    ((select id from zones where name='Потери'), (select id from sections where name=''),'При приемке товар взвешивается, пересчитывается. Товар на пол не ставится. Разбор поставки не более 1,5 часов (ВЗ), не более 1 часа - тесто', default),
    ((select id from zones where name='Потери'), (select id from sections where name=''), 'Продукты не размораживаются в ГЦ и ХЦ, мойке, на печи. Не лежат на столах более чем 30 минут. Одновременная заготовка не более 1 ингредиента одним сотрудником', default),
    ((select id from zones where name='Потери'), (select id from sections where name=''), 'На линиии начинения на каждый сыпучий ингредиент есть отдельный стаканчик. Используются актуальные стаканчики.', default),
    ((select id from zones where name='Курьеры'), (select id from sections where name=''), 'У всех сумок есть место для хранения ,не хранятся на полу.', default),
    ((select id from zones where name='Курьеры'), (select id from sections where name=''), 'Внешний вид курьеров соответствует стандарту.', default),
    ((select id from zones where name='Кассир'), (select id from sections where name=''), 'Ответственный сотрудник не оставляет открытым денежный ящик.', default),
    ((select id from zones where name='Касса'), (select id from sections where name=''), 'Кассир дружелюбен, моментально реагирует на гостя. Принимает заказы быстро, помогает с выбором. Не игнорирует гостя, не стоит спиной к нему, в закрытой позе. Реакция на звонок не более 30 секунд.', default ),
    ((select id from zones where name='Касса'), (select id from sections where name=''), 'Заказы в ресторан выданы на подносе согласно стандарту комплектации заказов. Гостю выдан чек (РБ). Пицца на металлическом подносе выдана согласно стандарту.', default),
    ((select id from zones where name='Тесто'), (select id from sections where name=''), 'Тесто хранится и используется по стандарту, на раскатке одновременно не более 6-и плюшек.', default),
    ((select id from zones where name='Кухня'), (select id from sections where name=''), 'Линия полностью заполнена гастроемкостями - герметична. При отсутствии заказов линия и гастроемкости закрыты.', default ),
    ((select id from zones where name='Кухня'), (select id from sections where name=''), 'Условия хранения продуктов и расходников соответствует стандартам (температура, 15 см от пола, пищевое/непищевое). В желтой зоне нет вскрытых упаковок с напитками.',  default),
    ((select id from zones where name='Кухня'), (select id from sections where name=''), 'Овощи моются по стандарту, необработанные овощи не кладут на столы в ГЦ и ХЦ.', default ),
    ((select id from zones where name='Кухня'), (select id from sections where name=''), 'Пиццы готовятся согласно принципу конвейера.', default ),
    ((select id from zones where name='Ресторан'), (select id from sections where name=''), 'Зал: чистый пол, нет следов от ботинок, сильных загрязнений.', default ),
    ((select id from zones where name='Ресторан'), (select id from sections where name=''), 'Чистые столы. Подносы убираются в течение пяти минут, нет остатков еды на убранных столах.', default),
    ((select id from zones where name='Сотрудник'), (select id from sections where name=''), 'Руки моются и обрабатываются антисептиком в соответствии со стандартом мытья рук.', default),
    ((select id from zones where name='Чистота'), (select id from sections where name=''), 'Посуду моют согласно стандарту', default),
    ((select id from zones where name=''), (select id from sections where name=''), 'Фотоотчет витрины 11:00,15:00,19:00. Без ошибок', default),
    ((select id from zones where name='Чистота'), (select id from sections where name=''), 'Чистая линия начинения и стол раскатки, убирается вовремя и по стандарту.- если мусор собрали в руку - руки помыты.', default),
    ((select id from zones where name=''), (select id from sections where name=''), 'Пицца-соус и альфредо закрывают крышкой при отстутствии заказов. Половник меняют каждые два часа. - если хранится в соусе.',default),
    ((select id from zones where name='Чистота'), (select id from sections where name=''), 'Уборка по стандарту, если не смыта химия со столешниц - критический фактор. Уборка происходит только в перчатках.',  default),
    ((select id from zones where name='Чистота'), (select id from sections where name=''), 'Чисто в пищевой зоне (столы,полки, стены, пол, раковины, микроволновки, урна не переполнена)', default ),
    ((select id from zones where name='Чистота'), (select id from sections where name=''), 'Чисто в непищевой зоне (двери, колодец, стыки, стены, пол). Все проходы свободны , не захламлены , отсутствуют мусорные мешки, можно пройти без препятствий.', default ),
    ((select id from zones where name='Чистота'), (select id from sections where name=''), 'Менеджерской зона: чистота и порядок, отсутствуют напитки рядом с оборудованием.', default ),
    ((select id from zones where name='Чистота'), (select id from sections where name=''), 'Химия и уборочный инвентарь хранится согласно стандарту. Уборочный инвентарь чистый.', default),
    ((select id from zones where name=''), (select id from sections where name='WOW фактор'), 'Идеальный додстер', default),
    ((select id from zones where name=''), (select id from sections where name='Критический фактор'), 'Уберите балл, за то, что считаете особо важным, чему не уделяют на смене внимание', -4),
    ((select id from zones where name=''), (select id from sections where name='Критический фактор'), 'Критическое нарушение пищевой безопасности.', -8),
    ((select id from zones where name='Менеджер'), (select id from sections where name=''), 'В пиццерии чисто во всех зонах, все сотрудники уходят домой вовремя. Менеджер проверяет качество закрытия пицц и кассира.', default),
    ((select id from zones where name='Менеджер'), (select id from sections where name=''), 'Заполнены журналы ХАССП', default ),
    ((select id from zones where name='Менеджер'), (select id from sections where name=''), 'Внесены списания, к ним есть комментарии. Перемещения закрыты', default),
    ((select id from zones where name='Менеджер'), (select id from sections where name=''), 'Кассовая смена пиццерии закрыта вовремя.', default),
    ((select id from zones where name='Менеджер'), (select id from sections where name=''), 'Выключены: печь, планшеты, экран мотивации, УФ Рециркуляторы, кофемашина. Свет во всех помещениях', default),
    ((select id from zones where name='Пиццамейкер'), (select id from sections where name=''), 'Нагретое тесто списано после окончания продаж',  default),
    ((select id from zones where name='Пиццамейкер'), (select id from sections where name=''), 'Продукты из линии занесены в холодильник, все стаканчики из лексанов убраны на мойку.',  default),
    ((select id from zones where name='Пиццамейкер'), (select id from sections where name=''), 'Уборка в ГЦ - зона раскатки и начинения - согласно стандарту уборки в закрытие.',  default),
    ((select id from zones where name='Пиццамейкер'), (select id from sections where name=''), 'Уборка в ГЦ - зона упаковки и хранения коробок - согласно стандарту уборки в закрытие.',  default),
    ((select id from zones where name='Пиццамейкер'), (select id from sections where name=''), 'Уборка в ХЦ - зона растарки, раковина для мытья рук и овощей, столы заготовки - согласно стандарту уборки в закрытие.', default),
    ((select id from zones where name='Пиццамейкер'), (select id from sections where name=''), 'Все мусорки опустошены, помыты изнутри. Инвентарь для уборки помыт после уборки всех зон.',default ),
    ((select id from zones where name='Пиццамейкер'), (select id from sections where name=''), 'Посуда чистая, помыта строго по стандарту, сушат по стандарту. На мойке чистота и порядок в хранении после ухода со смены.', default),
    ((select id from zones where name='Кассир'), (select id from sections where name=''), 'Витрина пополнена на 100%', default),
    ((select id from zones where name='Кассир'), (select id from sections where name=''), 'Выключены: тв-борды, кассовый моноблок, планшеты, свет в витрине + витрина закрыта шторкой, кофемашина, блендер.', default),
    ((select id from zones where name='Кассир'), (select id from sections where name=''), 'Уборка в зале: полы, столы, стулья, диваны, под мебелью, детская игровая, мусорки, туалет для гостей - качественно и по стандарту.', default ),
    ((select id from zones where name='Кассир'), (select id from sections where name=''), 'Уборка в кассовой зоне: столешницы, полки, зона выдачи заказов, пол, оборудование - качественно и по стандарту.', default ),
    ((select id from zones where name=''), (select id from sections where name='WOW фактор'), 'Сотрудник выполнил то, что другие не успевали на смене ранее',default  ),
    ((select id from zones where name='Менеджмент'), (select id from sections where name=''), 'Форма всех сотрудников соответствует стандарту.Сотрудники не используют личные телефоны в зеленой зоне пиццерии, не носят их в карманах.', default),
    ((select id from zones where name='Чистота'), (select id from sections where name=''), 'Чистый пол в пищевой зоне - не дольше 30 минут грязь от раскатки и линии, в пиковые дни пт сб и вс не оцениваем.',default);

