--liquibase formatted sql
--changeset Bubunur:insert_criteria_pizzarias

insert into criteria_pizzeria(criteria_id, pizzeria_id)
values
    ((select id from criteria where description = 'Форма всех сотрудников соответствует стандарту. Сотрудники кухни (кассир при работе на упаковке) с бородой на всех станциях носят набородник'), (select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Менеджер смены делает обходы.'),(select id from pizzerias where name = 'Борисов-1') ),
    ((select id from criteria where description = 'Сотрудники не используют личные телефоны в зеленой зоне пиццерии, не носят их в карманах'),(select id from pizzerias where name = 'Борисов-1') ),
    ((select id from criteria where description = 'Продукт готовится по стандарту. Соблюдаются стандарты начинения, приготовления продукта, упаковки.  Нет перерасхода ингредиентов. До 3-х ошибок, 4 и более - крит. фактор'),(select id from pizzerias where name = 'Борисов-1') ),
    ((select id from criteria where description = 'При приемке товар взвешивается, пересчитывается. Товар на пол не ставится. Разбор поставки не более 1,5 часов (ВЗ), не более 1 часа - тесто'),(select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Продукты не размораживаются в ГЦ и ХЦ, мойке, на печи. Не лежат на столах более чем 30 минут. Одновременная заготовка не более 1 ингредиента одним сотрудником'),(select id from pizzerias where name = 'Борисов-1') ),
    ((select id from criteria where description = 'На линиии начинения на каждый сыпучий ингредиент есть отдельный стаканчик. Используются актуальные стаканчики.'),(select id from pizzerias where name = 'Борисов-1') ),
    ((select id from criteria where description = 'У всех сумок есть место для хранения ,не хранятся на полу.'),(select id from pizzerias where name = 'Борисов-1') ),
    ((select id from criteria where description = 'Внешний вид курьеров соответствует стандарту.'),(select id from pizzerias where name = 'Борисов-1') ),
    ((select id from criteria where description = 'Ответственный сотрудник не оставляет открытым денежный ящик.'),(select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Кассир дружелюбен, моментально реагирует на гостя. Принимает заказы быстро, помогает с выбором. Не игнорирует гостя, не стоит спиной к нему, в закрытой позе. Реакция на звонок не более 30 секунд.'),(select id from pizzerias where name = 'Борисов-1') ),
    ((select id from criteria where description = 'Заказы в ресторан выданы на подносе согласно стандарту комплектации заказов. Гостю выдан чек (РБ). Пицца на металлическом подносе выдана согласно стандарту.'), (select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Тесто хранится и используется по стандарту, на раскатке одновременно не более 6-и плюшек.'), (select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Линия полностью заполнена гастроемкостями - герметична. При отсутствии заказов линия и гастроемкости закрыты.'),(select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Условия хранения продуктов и расходников соответствует стандартам (температура, 15 см от пола, пищевое/непищевое). В желтой зоне нет вскрытых упаковок с напитками.'),(select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Овощи моются по стандарту, необработанные овощи не кладут на столы в ГЦ и ХЦ.'),(select id from pizzerias where name = 'Борисов-1') ),
    ((select id from criteria where description = 'Пиццы готовятся согласно принципу конвейера.'), (select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Зал: чистый пол, нет следов от ботинок, сильных загрязнений.'),(select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Чистые столы. Подносы убираются в течение пяти минут, нет остатков еды на убранных столах.'),(select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Руки моются и обрабатываются антисептиком в соответствии со стандартом мытья рук.'),(select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Посуду моют согласно стандарту'), (select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Чистая линия начинения и стол раскатки, убирается вовремя и по стандарту.- если мусор собрали в руку - руки помыты.'),(select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Пицца-соус и альфредо закрывают крышкой при отстутствии заказов. Половник меняют каждые два часа. - если хранится в соусе.'), (select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Уборка по стандарту, если не смыта химия со столешниц - критический фактор. Уборка происходит только в перчатках.'),(select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Чисто в пищевой зоне (столы,полки, стены, пол, раковины, микроволновки, урна не переполнена)'),(select id from pizzerias where name = 'Борисов-1') ),
    ((select id from criteria where description = 'Чисто в непищевой зоне (двери, колодец, стыки, стены, пол). Все проходы свободны , не захламлены , отсутствуют мусорные мешки, можно пройти без препятствий.'), (select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Менеджерской зона: чистота и порядок, отсутствуют напитки рядом с оборудованием.'),(select id from pizzerias where name = 'Борисов-1') ),
    ((select id from criteria where description = 'Химия и уборочный инвентарь хранится согласно стандарту. Уборочный инвентарь чистый.'), (select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Идеальный додстер'), (select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Уберите балл, за то, что считаете особо важным, чему не уделяют на смене внимание'),(select id from pizzerias where name = 'Борисов-1')),
    ((select id from criteria where description = 'Критическое нарушение пищевой безопасности.'),(select id from pizzerias where name = 'Борисов-1') );