<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>


<div class="gallery_functionality">
    <div class="grid">
        <div class="grid-item">
            <a data-fslightbox="gal" href="/1.jpg">
                <img src="/1.jpg" alt="image">
            </a>
        </div>
        <div class="grid-item">
            <a data-fslightbox="gal" href="/1.jpg">
                <img src="/1.jpg" alt="image">
            </a>
        </div>
        <div class="grid-item">
            <a data-fslightbox="gal" href="/1.jpg">
                <img src="/1.jpg" alt="image">
            </a>
        </div>
        <div class="grid-item">
            <a data-fslightbox="gal" href="/1.jpg">
                <img src="/1.jpg" alt="image">
            </a>
        </div>
    </div>
</div>


<script src="/js/fslightbox.js"></script>

</body>
</html>